# Generated by Django 6.0.5 on 2026-05-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('session_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_policy', models.CharField(choices=[('TOTAL', 'Total upfront'), ('50_DEPOSIT', '50% deposit'), ('EXTERNAL', 'Pay in office')], max_length=20)),
                ('modality', models.CharField(choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In-person'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'psychologists',
            },
        ),
    ]
