# Generated by Django 6.0.5 on 2026-05-26 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('FULL_BOOKING', 'Full booking'), ('50_DEPOSIT', '50% deposit')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], max_length=20)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='appointments.appointment')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
